---
title: " "
output: html_document
---

<style>
  .nav-pills>li>a:hover, 
  .nav-pills>li>a:focus, 
  .nav-pills>li.active>a,     
  .nav-pills>li.active>a:hover, 
  .nav-pills>li.active>a:focus{
     background-color: #990000;
     }

a:link {
  color: #990000;
}

a:visited {
  color: #BD0000;
}

a:hover {
  color: #A7A9AB;
}

a:active {
  color: #990000;
}
</style>


<br>

<center>
<h1 style="color:#990000">**Frequently asked questions**</h1>
</center>

#### We love when people get involved with the lab and contact us. That said, there are some questions we find ourself answering a lot. This (in progress) part of the webpage has answers to questions I often get:{.tabset .tabset-pills}

#####  Potential students (undergraduate)

This section is still "in progress." Please check back at a later date.

##### Potential students (graduate)

*Please note: For this document, I borrowed **very heavily** from a similar document by [Prof. Jessica Schleider](https://www.stonybrook.edu/commcms/psychology/faculty/faculty_profiles/jschleider) at [Stony Brook University](https://www.stonybrook.edu/). Apply to work with her as well! Below are some questions I have gotten, or anticipate getting from potential graduate students*:
 
**Why make this?**
Applying to graduate school is currently an uneven "playing field." Applicants without access to well-established mentors, parents who have graduate degrees, or other professional connections may have less access to information on how to apply for school. I hope that by sharing inside knowledge on my process, I can level the playing field a little, at least when applying to work with me. <br> Please note that the document represents my personal opinions. It is therefore not representative of Indiana University, my home department Psychological and Brain Sciences, or of any other faculty members in our program.
 
**Will you be accepting a new PhD student to begin in Fall 2022?**
As of right now `r Sys.Date()`, I will **not** be accepting new students. The only thing that could happen to change my decision is if you were coming in with your own funding!

**Are my interests a good for for the lab?**

Applicants with the following interests may be good fits to our lab:
- Scalable, brief and **low-intensity** psychosocial interventions, especially web-based and self-administered interventions (e.g., guided bibliotherapy) for reducing depression and anxiety
- **Dissemination** of mental health services beyond traditional clinical settings
- Studying **predictors and moderators** of treatment outcomes in cognitive-behavioral therapies (CBTs) for depression and anxiety
- Studying **processes** of change in cognitive-behavioral therapies (CBTs) and other treatments for depression and anxiety
- Using advanced **quantitative methods** to study questions of change in psychotherapy
- Measuring vulnerability to common mental disorder via **social media**. (This would require collaboration with our colleagues at Informatics)

As a mentor, I feel best-prepared to support students who are interested in careers that involve applied research. This includes a wide variety of career paths, including academic faculty positions, e.g. in departments of psychology, education, social work, or public health; and combined clinical-research careers, e.g. in academic medical centers.

I may not be the most effective mentor for applicants who are interested entirely in clinical practice careers as my clinical practice has only ever been part-time.

**How can I learn more about you and your research?**
Below are the papers that are most representative of how I think about depression:
- Lorenzo-Luaces, L. (2015). Heterogeneity in the prognosis of major depression:  From the common cold to a highly debilitating and recurrent illness. *Epidemiology and Psychiatric Sciences*, 24, 466-472.
- Lorenzo-Luaces, L, DeRubeis, R.J., van Straten, A., & Tiemens B. (2017). A prognostic index (PI) as a moderator of outcomes in the treatment depression: A proof of concept combining multiple variables to inform risk-stratified stepped care models. *Journal of Affective Disorders*, 213, 78-85.
- Lorenzo-Luaces, L., Rodriguez-Quintana, N.,* Riley, T., & Weisz, J.R. (2020) A prognostic index (PI) as a moderator of outcomes in the treatment of adolescent depression: A risk-stratified stepped care model of treatment with cognitive-behavioral therapy, fluoxetine, or their combination. Psychotherapy Research. Advanced online publication.
- Lorenzo-Luaces, L., DeRubeis, R.J., & Webb, C.A. (2014). Client characteristics as moderators of the relation between the therapeutic alliance and outcome in cognitive therapy for depression. Journal of Consulting and Clinical Psychology, 82, 368 – 373.

**What about the GRE? How important are my scores?**
I don’t care about it, I won’t look at it. The only time in which I may consider your GRE is if you explicitly mention that your undergraduate GPA is low but you would like your GRE considered because it “makes up” for a lower GPA.

**My undergraduate GPA is below 3.5 (or some other number). Will this remove me from consideration?**
No. Many factors can influence one’s GPA, including competing commitments (e.g., working part-time while in school), family obligations, and health challenges. Academic achievement is very important, but context is, too. If you believe your GPA does not reflect your potential as a future scientist, please either ask one of your recommenders to share more about your circumstances to help me assess your achievements, or provide this information in your personal statement in a measured manner that you feel comfortable with. For example, if your undergraduate GPA is low because you were in an unhealthy relationship, you can simply say you had "personal problems."

**Should I email you to express my interest in applying to your lab?**
It's not needed. Although I welcome emails from prospective students with specific questions, your decision to email me (or not) will have no impact on your odds of receiving an interview invitation or an offer of admission. Whether or not you contact me in advance, prospective students are encouraged to review our online materials, including our publications and our lab website sadcatlab.com

**I am primarily interested in treatment of bipolar depression. You have published on this. Does this mean I’m a good fit for your lab?**
It depends, we’d have to talk about it. I have collaborators who have conducted studies of bipolar II depression and therefore have some data for someone interested in this topic. However, it’s not my primary interest. If your interests included bipolar disorder (e.g., how are unipolar and bipolar disorder different) then that would probably be a good fit but if your interests were exclusive to bipolar, especially bipolar I (e.g., what cognitive factors maintain mania), then it’d be less of a fit. This would be a good reason to e-mail me!

**I am interested in studying therapeutic alliance, relational processes in psychotherapy, and/or the effectiveness of traditional (face-to-face, clinic-based) treatments. Should I consider your lab? **
Yes! You’ll note from my CV that this is something I am interested in. While the projects we have exploring psychotherapy processes are fewer and far between, the topic is important to me so I would welcome students who are interested!

**I want to study depression and scalable treatments but I don’t have experience with that research topic. Can I still apply to your lab?**
Yes! My main aim is to recruit people who have research experience, in general. Most of the skills you developed should translate, it will be a matter of reading the content area knowledge.  If you have not engaged in depression research before, please note in your personal statement why you are interested in it and how you other research informs what you may think about depression.  
 
**What should I include in my personal statement?**
I find it helpful when applicants include the following in their personal statements:

1. A clear statement of your general research interests and how they relate to our lab’s mission and work
2.  A statement about your career goals (even if they are approximate/might change)
3.  Discussions of your independent research experience(s) and what you learned from them. In these discussions, I suggest emphasizing (1) the question that the broader research was trying to answer, (2) the skills you developed from working on each project (e.g., data collection in Qualtrics; coding/running analyses; interviewing children/families; writing certain sections of a paper; submitting/presenting a poster), and (3) what your “takeaways” were from the project—e.g., new research ideas or questions your work inspired.
 
**I am interested in becoming a therapist or incorporating clinical practice into my future career. I’ve heard that mentioning this in my application will hurt my admissions chances. Is this true?** 
I aim to recruit students seeking rigorous training in both intervention research and clinical practice. Both skill-sets inform each other necessarily. Our lab tests interventions, so I view clinical training as especially important for trainees in our lab. At the same time, Indiana University’s clinical psychology program has a very strong clinical *science* orientation, and students who are happiest in our program tend to want careers that incorporate research in some way. Consistent with this orientation, I may not be the most effective mentor for applicants who are interested entirely in clinical practice careers. Moreover, if you want a primarily clinical experience, the program won’t be good for you because you’ll have to balance teaching and research obligations so you won’t get as much hours as you might in a PsyD program or a PhD that emphasized research less.
 
**My own experiences with mental health problems (e.g., my own, a friend’s, or a relative’s) shaped my interest in making treatments better/more accessible. I’ve been told not to mention this in my personal statement. Is this true?** 
Speaking for only myself: no, for the most part. On the one hand, life experiences shape our career interests, trajectories, and goals in meaningful ways. There is nothing wrong with acknowledging intersections between our ‘human’ and ‘scientific’ selves. On the other hand, personal/lived experiences should not be the main focus of your personal statement. Your research interests, experiences, goals, and ‘fit’ to our lab are much more helpful to me when reviewing your application. So, it is ok to say something like: “I first learned about the lack of access to mental health treatment when seeking treatment for myself. My difficulty finding a provider made me interest in the empirical literature which documents that patients face long wait times before they can be seen. When I worked with Dr. Smith, his research sought to explore to what extent stigma made people more vs. less likely to overcome barriers to treatment.” To give you an example, I became interested in the validity of DSM diagnoses after a friend was diagnosed with bipolar “not otherwise specified.” But, this wasn’t enough to carry me all the way into grad school. I learned about the history of diagnoses and debates about their validity which caused me to purse a research project that was unrelated but gave me experience in mixed methods.
 
**Is it advantageous to list multiple mentors of interest (or just one) on my application?**
Yes, you should list multiple mentors of interest on your application! Our program is interdisciplinary and it is expected that you may want to work with others. I closely review all applications on which I am listed as a first-choice mentor. But, listing multiple mentors is important because part of our admission process involves making sure that there are other potential mentors in case the initial mentorship relation is not successful. Other professors who have similar interests include Profs. D’Onofrio (quantitative methods, treatment of internalizing disorders), Bates or Holtzworth-Munroe (psychosocial interventions), Krendl (stigma, treatment accessibility), and Green (emotion regulation and individual differences). 

**How do I know if I am a “good fit” for the SADCAT Lab?**
I review the applications of **all** the students who say the way to work with me. I rate the students and then send e-mails to around 10 people. Please note, I do not use a strict cut-off of 10 or even e-mail the 10 highest rated people. I consider the ratings and all the information to come up with a list of 10 students I want to get to know better. The factors I consider are:

1. **Overlap with the lab's interests and work.** Your interests overlap with mine if you want to research: A) the classification of affective problems, B) treatment outcomes in affective disorders, C) processes and mechanisms of psychopathology in and out of treatment, D) individual differences in outcomes and processes relevant to affective disorders, or E) social media and affective disorders. Please note, my primary focus is that you are *interested* in these topics, I don't expect you to necessarily have past experience with the topics. I also tend to value a student if they have interests that are a bit outside of my own too. For example, a student who was interested in processes of change in depression treatment and dissemination and implementation would probably be scored more highly than a student who was only interested in processes of change in depression treatment. I score this on a 0-1 scale where 0 = no overlap, 1 = expressed interests that overlap very well with the topics we study. 
2. **Research experience.** As I said above, you don't need to have past research experience in our content area to demonstrate interest but I do look for candidates who have a fair bit of research experience. A lot of the work that we do can quickly become complicated so I am looking for people who have a basic handle on research, usually around 2 years of part-time research experience. I understand that some of you have other obligations while you are in school, including having to work or take care of a loved one. I am happy to consider this as part of your application if you feel comfortable enough referencing it. The way I rate this is also on a 0 - 1 scale. I do this by counting the number of months of research experience for each candidate on a given year. Then, I look at the distribution of scores and put a cap on a maximum. For example, if the highest person has been working in research 10 years but the next highest person has been working a lot less, like 2 years, 2 years becomes the max I use to "standardize" the scores. So, the 10 becomes a 2 (i.e., I "winsorize" extreme values) and I standardize the experience by dividing all the scores by the max, here a 2. That way, I can also rate this on a 0-1 scale where 0 is the lowest research experience represented and 1 is the highest.<br> I’m especially interested in recruiting applicants with experiences in some or all of the following areas (however, none is required of applicants): randomized clinical trial(s), digital mental health interventions, coding or programming, collecting or analyzing ecological momentary assessment data.
3. **Contributions to diversity in our program/lab.** I care about the lack of diversity in academia, which is a major problem in many fields. If a student would diversify the student body at my lab or in our department, I would consider that a major positive.
4. **Quality of the personal statement.** I don't really know how to explain *how* I rate this, I just do. One of the things I just look is as a writing sample. Not in the sense of detecting typos or grammar errors, neither of which I care about, but in the sense of helping me understand how you communicate and the things about your experience that you choose to highlight. Also rate this on a 0-1 scale.
5. **Grade point average (GPA) in school.** Pretty straightforward, I look at GPA. The way I do with research experience, I put a cap on the maximum, here it's 4.0 (sorry 4.5 GPAs!). Then I convert these ratings to 0-1 by dividing by 4.
6. **Evidence of post-baccalaureate or graduate work.** If you have done a master's degree or post-bac to further your education, I count that as a plus! 
7. **Quality of letters.** Getting recommendation letters early in one's career is very difficult! I basically expect only one relatively glowing recommendation letter written by someone you worked closely with. I don't care if the person is a graduate student or the CEO of Research, Inc. A lot of people will also have a letter that may be very brief, relatively unspecific, or from a professor who may know you are very smart and talented but has had somewhat limited interactions with you. That is OK. I expect the third letter will be somewhat in between the two I already discussed. This kind of set-up (long/glowing, brief/non-specific, and "medium") is what I'm expecting most people to have and gets an 8/10. Anything less gets a lower score and if you happen to have more than that


**Are there any other ‘screening criteria’ you use to review applications?**
No. You work hard on your application materials. The least I can do is read them! (And I do read all applications from those who indicate that I am their preferred mentor.)
 

 
**Can I reach out to current PhD students in your lab if I have questions about your lab?**
Certainly! Their email addresses are available on our lab website
 


This guide was originally developed by Jessica Schleider, PhD, and was adapted for the SADCAT Lab with the latest version adapted in `r Sys.Date()`
 

