---
title: ""
---

<center>
<h1 style="color:#990000">**Media**</h1>
</center>


06-14-2023: The [Shared Experiences](https://www.youtube.com/@sharedexps) podcast asked me to talk about [depression in men](https://youtu.be/zPTbgwR_JI4)

02-24-2021: Here is a presentation at the Clinical Science Colloquium at [Stony Brook](https://www.stonybrook.edu/commcms/psychology/). The focus here is our work on the [heterogeneity of depression and its influence on treatments processes and outcomes](https://www.instagram.com/p/CK4PgrXJQI4/?utm_source=ig_web_button_share_sheet&fbclid=IwAR36i3DCTLaiz8OEnxUKJwrPzirLm9FPFtOcp6J9j7OeuRHf6nsMrjIOFcI)

11-15-2020: Here is a presentation at the Association for Behavioral and Cognitive Therapy's Annual Meeting with a focus on [extracting circadian rhythms from social media data](https://www.facebook.com/IUDepressionLab/videos/375320280206176)

11-11-2020: Here is a presentation at the Clinical Science Colloquium at [Boston University](https://www.bu.edu/psych/academics/phd/clinical/). The focus here is our work on the [heterogeneity of depression and its influence on treatments processes and outcomes](https://www.facebook.com/watch/?v=385299209340711)

10-12-2020: IU Psychology professor Rick Hullinger asked me to share how I developed my [research interests](https://www.facebook.com/watch/?v=796455577815181)


